title: RaHub4AI
description: Website for our research group
baseurl: ""
url: "https://rahub4ai.github.io"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  pages:
    output: true
    permalink: /:path/
